In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [6]:
df = pd.read_csv('movies_metadata.csv')

# **Data Cleaning & Gathering**

In [7]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [8]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [10]:
df.shape # rows & columns

(45466, 24)

In [11]:
df.isnull().sum() # number of null values in each column
# e.g.: there are 954 row entries whose 'overview' column in null

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [12]:
# 13 duplicated rows were present, so drop them
df = df.drop_duplicates().reset_index(drop = True)

In [13]:
df.duplicated().sum() # check again if correctly dropped

np.int64(0)

In [14]:
# relevant columns are included, irrelevant columns dropped
df = df[['title', 'overview', 'genres', 'tagline', 'vote_average', 'popularity']]

In [15]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [16]:
df.isnull().sum() # null values in each column

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [17]:
df = df.dropna(subset = ['title']) # remove null values of 'title' column

In [18]:
df.isnull().sum()

title               0
overview          954
genres              0
tagline         25039
vote_average        0
popularity          0
dtype: int64

In [19]:
# 954 rows in 'overview` column have null values
# fill them with empty spaces instead of NaN

df['overview'] = df['overview'].fillna('')

In [20]:
# work on genres
# 3 genres : Animation, Comedy, Family

df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [21]:
import ast

# converting
# [{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
# to
# Animation Comedy Family

In [22]:
# Create a lambda expression for conversion of genres

df['genres'] = df['genres'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]))

In [23]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [24]:
# filling 25k NaN rows of 'tagline' column with empty spaces

df['tagline'] = df['tagline'].fillna('')

In [25]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [26]:
# combine these columns so that we can vectorize them at once instead of doing one by one

df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline']

In [27]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

# **NLP Text Pre-processing**

In [30]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [32]:
# Remove punctuations - don't impact the sentence much. [, -- ' etc....]
# Remove stop-words like [when, the, and, an, that, the, to, a]

# Split words and create tokens out of them
# Use Limitization before creating tokens

# Stemming & Lemmatization :
# both are text preprocessing techniques in NLP, used to reduce words to their base or root forms
# Stemming uses crude rule-based suffix stripping
# Lemmatization uses vocabulary and grammar context to return valid dictionary word (lemma)

# Example:
# 'end' & 'ending' -- both are same, but in different forms
# take 'ending' to its root form i.e., 'end'

In [33]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [34]:
# downloading packages
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [35]:
# create objects of stopwords & wordnet

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [36]:
# Function created to apply on 'tags'
def preprocess_text(text):

  # lower case
  text = str(text).lower()

  # remove punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  # tokenization
  words = text.split()

  # remove stopwords
  # word which is present in 'words' and not in 'stop_words' - REMAIN
  # word which is present in 'words' and in 'stop_words' - REMOVED
  words = [word for word in words if word not in stop_words]

  # lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [37]:
# before preprocessing
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [38]:
# Apply preprocessing function on 'tags'
df['tags'] = df['tags'].apply(preprocess_text)

In [39]:
# after preprocessing
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [40]:
df['tags'][0]

'led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

# **Text Vectorization**

In [41]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [42]:
# When we removed duplicates, indices of those also gets removed
# We need to reset the indices to bring uniformity

df = df.reset_index(drop = True)

In [43]:
# Create a series of the indices using pandas

indices = pd.Series(df.index, index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [44]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [45]:
# Apply vectorization on tags
# Convert the long sentences into numbers using TF-IDF

# One Hot Encoding - Create a vector for every word
# Vector shape was dependent on number of words

# Bag of Words - use Vocabulary
# Forgets word order, misses the context

# TF-IDF
# Used to score how important a word is to a document within large collection of text

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [48]:
# ngram_range(min, max)
# tells your vectorizer minimum and maximum size of these word sequences to extract

# Example : [ the cat sits ]
# ngram_range(1, 1) : "the", "cat", "sits"
# ngram_range(1, 2) : "the", "cat", "sits", "the cat", "cat sits"

In [49]:
tfidf = TfidfVectorizer(max_features = 50000, ngram_range = (1,2), stop_words = 'english')

In [50]:
# 'tags' converted into a 2d matrix
# we have 45447 movies in our dataframe
# for every movie out of 45447 movies, a vector of size 50000 is created
# the matrix shape - [45447][50000] - (rows : 45447, columns : 50000)

tfidf_matrix = tfidf.fit_transform(df['tags'])

In [52]:
tfidf_matrix # Shape of matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548114 stored elements and shape (45447, 50000)>

# **Cosine Similarity**
- A metric used to measure how similar two text documents are, regardless of their size.
- It calculates cosine of the angle between two multi-dimensional vectors projected in a geometric space
- In text processing, closer the final score is to 1, more similar the context of documents
- cos(0) = 1 | cos(45) = 0.71 | cos(90) = 0

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
# n is number of movies to recommend based on given movie 'title'

def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]

  # use cosine similarity to compare given movie with all other movies
  similarity_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()

  # argsort() : sort on basis of index
  # use index slicing to extract top 10
  similar_idx = similarity_score.argsort()[::-1][1:n+1]

  return df['title'].iloc[similar_idx]

In [56]:
recommend('Toy Story')

2996                Toy Story 2
15344               Toy Story 3
24512                 Small Fry
28972           Superstar Goofy
17184                 Group Sex
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1071      Rebel Without a Cause
1931                  Condorman
485                      Malice
Name: title, dtype: object

In [57]:
recommend('Avengers')

['Movie not found']

In [58]:
recommend('Small Fry')

0                                      Toy Story
24126                                     Aladin
8079           Harold & Kumar Go to White Castle
15386                              Mercy Streets
8109                                  Triggermen
13757                      The Wing or the Thigh
40839    An American Girl: Chrissa Stands Strong
45253                       Hemo The Magnificent
26104                            Switching Goals
12861                                  Gigantics
Name: title, dtype: object

In [59]:
recommend('Rebel Without a Cause')

18072                   Tomboy
1081             The Sleepover
26338    Soccer Dog: The Movie
24512                Small Fry
0                    Toy Story
45007            Inconceivable
35621          Science Fiction
20298                    Sunny
25446                     1981
36956        Good Boy, Bad Boy
Name: title, dtype: object

In [60]:
recommend('Avatar', 5)

26547                  Avatar 2
13883      The Inhabited Island
26553            Thor: Ragnarok
43431    Moontrap: Target Earth
14119      The Three Musketeers
Name: title, dtype: object

In [61]:
recommend('Thor')

21932                          Thor: The Dark World
17491                                 Almighty Thor
38830                                     I Am Thor
20788                         Thor: Tales of Asgard
26553                                Thor: Ragnarok
41145                                     Team Thor
44234                               Prince of Space
35242    Marvel Super Hero Adventures: Frost Fight!
19524                                      Kon-Tiki
22465                      Dragon Ball Z: Lord Slug
Name: title, dtype: object

# Creating Pickle Files

In [62]:
import pickle

# use tfidf matrix and open a pickle file, saved in read binary format
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

pickle.dump(indices, open('indices.pkl', 'wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf, open('tfidf.pkl', 'wb'))